### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by cyrusDev1** [raminmr/free-api-worldcup2022#46]
Access to fetch at 'http://api.cup2022.ir/api/v1/bydate' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by cyrusDev1** [comment]
@raminmr

**Comment by bassil-97** [comment]
I have the same issue

**Comment by vinibaccin** [comment]
Same issue here @raminmr

**Comment by raminmr** [comment]
Are you calling directly through the website?

**Comment by raminmr** [comment]
> Are you calling directly through the website?


Are you calling directly through the website?

**Comment by raminmr** [comment]
> Access to fetch at 'http://api.cup2022.ir/api/v1/bydate' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.


Are you calling directly through the website?

**Comment by cyrusDev1** [comment]
> > @raminmr me too
> 
> Are you calling directly through the website?


I used axios to make the request from the api

**Comment by cyrusDev1** [comment]
it works fine on postman but not in browser

**Comment by raminmr** [comment]
My Brother
You must call through the service server. You cannot call the service through the web.

**Comment by cyrusDev1** [comment]
What can i do?

**Comment by Brenno-Ribeiro** [comment]
@raminmr 

How connetion in service server.

**Comment by irlanviana** [comment]
@raminmr 
How can I connect through the service server?

**Comment by sp1z** [comment]
How are you all trying to connect?  If you're just clicking the link in a browser that won't work, you'll need to use some sort of JSON API library.

**Comment by irlanviana** [comment]
@sp1z through Axios

**Comment by bassil-97** [comment]
I’ve tried to call the api from localhost (react app) through axios (I am using a web token also) , but CORS error is showing up saying that I cannot send requests from localhost to the api‫أُرسلت من الـ iPhone‬‫في ١٢‏/١١‏/٢٠٢٢ الساعة ٢:٠٧ م، كتب/كتبت ‏Irlan Viana ***@***.***>:‬﻿
@sp1z through Axios

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

The
content of this email and its attachments and any views or opinions presented
in this email are solely those of the sender and do not represent those of the
Yarmouk University. Also, the recipient should check this email and any
attachments for the presence of viruses. Yarmouk University will not
accept any liability in respect of such communication or
any damage caused by any virus transmitted by this email or its attachments,
and the sender will be personally liable for any damages or other liability
arising.

©Yarmouk
University, Irbid-Jordan www.yu.edu.jo

**Comment by raminmr** [comment]
You must call through the service server. You cannot call the service through the web.

If you want to call the service directly. support me I will give you access to your address 🤪

**Comment by ahocevar99** [comment]
What exactly does it mean to call through the service server?
